version: '3.1'
services:

  articles-blog:
    build: .
    container_name: articles
    ports:
      - "8080:8080"
    depends_on:
      - articles-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://articles-db:5432/db
      SPRING_DATASOURCE_USERNAME: articles_user
      SPRING_DATASOURCE_PASSWORD: articlespass

  articles-db:
    image: postgres:14-alpine
    volumes:
      - articles-data:/var/lib/postgresql/data
    container_name: postgres_articles
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: articlespass
      POSTGRES_USER: articles_user
      POSTGRES_DB: db

volumes:
  articles-data: